[package]
name = "media_hub"
version = "0.1.0"
authors = ["Brian McNamara <brianmay27@gmail.com>"]

[dependencies]
hyper = "0.12.5"
base64 = "0.9.2"
hyper-tls = "0.3.0"
futures = "0.1"
http = "0.1.7"
config = "0.9.0"